// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjwuBbh5wMXQcStvIuPzW7e-H1_D3EQQk',
    appId: '1:212412695795:web:988ddb2e9226b81f57e386',
    messagingSenderId: '212412695795',
    projectId: 'activite-group',
    authDomain: 'activite-group.firebaseapp.com',
    storageBucket: 'activite-group.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB6Sq1SZD3guOn4BWLk2XzrjNxIksVvNI',
    appId: '1:212412695795:android:7663c69d1512b51257e386',
    messagingSenderId: '212412695795',
    projectId: 'activite-group',
    storageBucket: 'activite-group.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArtdbxdmjZzXBwW0RMyLQcgRjkc9x0Ud0',
    appId: '1:212412695795:ios:5d10d6a4f04bbaeb57e386',
    messagingSenderId: '212412695795',
    projectId: 'activite-group',
    storageBucket: 'activite-group.appspot.com',
    iosBundleId: 'com.example.activiteGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArtdbxdmjZzXBwW0RMyLQcgRjkc9x0Ud0',
    appId: '1:212412695795:ios:1afff5aedaee6f4057e386',
    messagingSenderId: '212412695795',
    projectId: 'activite-group',
    storageBucket: 'activite-group.appspot.com',
    iosBundleId: 'com.example.activiteGroup.RunnerTests',
  );
}
